version: "3"
  
services:
  bookstack:
    image: "bookstack:latest"
    ports:
      - "8181:8181"
    volumes:
      - "/data/bookstack/conf:/bookstack/conf"
    depends_on:
      - mysql
    restart: always
    networks:
      - bookstack

  mysql:
    image: "mysql:8.0.23"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "bookstack"
      MYSQL_USER: "bookstack"
      MYSQL_PASSWORD: "bookstack123"
    volumes:
      - "mysql:/var/lib/mysql"
    restart: always
    networks:
      - bookstack    

networks:
  bookstack:

volumes:
  mysql: 
