name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BOOKSTACK_VERSION: v2.10
  DOCKERHUB_USERNAME: willdockerhub
  ALIYUN_USERNAME: willzhmic@outlook.com
  ALIYUN_REGISTRY_URL: registry.cn-shenzhen.aliyuncs.com


jobs:
  get-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Login aliyun registry
    - name: Login aliyun and docker registry
      run: |
        echo "${{ secrets.ALIYUN_PASSWORD }}" | docker login $ALIYUN_REGISTRY_URL -u $ALIYUN_USERNAME --password-stdin
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u $DOCKERHUB_USERNAME --password-stdin
        
    # pull retag and push images
    - name: get images
      run: |
        docker build . --file Dockerfile.node --tag willdockerhub/bookstack:${BOOKSTACK_VERSION}_node
        docker push willdockerhub/bookstack:${BOOKSTACK_VERSION}_node
